# Generated by Django 4.2.1 on 2023-05-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonapp', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
