# Generated by Django 4.2.1 on 2023-05-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonapp', '0003_myform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyForm',
            new_name='Reservation',
        ),
    ]
