# Generated by Django 4.2.1 on 2023-05-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonapp', '0004_rename_myform_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Reserve',
        ),
    ]
