# Generated by Django 4.2.1 on 2023-05-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonapp', '0005_rename_reservation_reserve'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
