# Generated by Django 5.1 on 2024-08-19 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonapp', '0007_manualreservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManualReservation',
            new_name='Booking',
        ),
    ]
